### ISSUE TITLE
Elemental Creepers v5.0.0 crashing Minecraft 1.8.x with latest Forge on startup

### ISSUE THREAD

**Issue by cemerson** [Lomeli12/ElementalCreepers-Rebooted#23]
## Forge Version: 
11.14.1.1334

## Details

- Minecraft only crashes when I have Creepers mod installed - game doesn't crash if I pull it out of the mods folder.

- I'm still looking into this in case it's something else but so far it seems like the above is the jist.

## Crash log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  DLFMLCorePlugin (DynamicLights-1.8.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 3/22/15 12:09 PM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 28
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:120)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:114)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:57)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:30)
	at net.minecraft.client.resources.model.ModelBakery.makeBakedQuad(ModelBakery.java:544)
	at net.minecraft.client.resources.model.ModelBakery.bakeModel(ModelBakery.java:529)
	at net.minecraftforge.client.model.ModelLoader.access$800(ModelLoader.java:62)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:267)
	at net.minecraftforge.client.model.ModelLoader$WeightedPartWrapper.bake(ModelLoader.java:313)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:370)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:105)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.renderer.block.model.FaceBakery.func_178404_a(FaceBakery.java:120)
	at net.minecraft.client.renderer.block.model.FaceBakery.fillVertexData(FaceBakery.java:114)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeQuadVertexData(FaceBakery.java:57)
	at net.minecraft.client.renderer.block.model.FaceBakery.makeBakedQuad(FaceBakery.java:30)
	at net.minecraft.client.resources.model.ModelBakery.makeBakedQuad(ModelBakery.java:544)
	at net.minecraft.client.resources.model.ModelBakery.bakeModel(ModelBakery.java:529)
	at net.minecraftforge.client.model.ModelLoader.access$800(ModelLoader.java:62)
	at net.minecraftforge.client.model.ModelLoader$VanillaModelWrapper.bake(ModelLoader.java:267)
	at net.minecraftforge.client.model.ModelLoader$WeightedPartWrapper.bake(ModelLoader.java:313)
	at net.minecraftforge.client.model.ModelLoader$WeightedRandomModel.bake(ModelLoader.java:370)
	at net.minecraftforge.client.model.ModelLoader.func_177570_a(ModelLoader.java:105)
	at net.minecraft.client.resources.model.ModelManager.func_110549_a(ModelManager.java:29)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110542_a(SourceFile:99)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:470)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:325)
	at net.minecraft.client.main.Main.main(SourceFile:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 84994944 bytes (81 MB) / 304353280 bytes (290 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.10 FML v8.0.37.1334 Minecraft Forge 11.14.1.1334 18 mods loaded, 18 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded
	FML{8.0.37.1334} [Forge Mod Loader] (forge-1.8-11.14.1.1334.jar) Unloaded
	Forge{11.14.1.1334} [Minecraft Forge] (forge-1.8-11.14.1.1334.jar) Unloaded
	animalbikes{1.7.10} [Animal Bikes] (AnimalBikes_1.8.0_beta.jar) Unloaded
	BattleTowers{1.5.2} [Battle Towers] (BattleTowers-1.8.jar) Unloaded
	dessertcraft{v1.4} [Dessertcraft] (Dessertcraft-1.4.jar) Unloaded
	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.8.jar) Unloaded
	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.8.jar) Unloaded
	ElementalCreepers{5.0.0} [Elemental Creepers] (Elemental Creepers-universal-1.8-5.0.0.jar) Unloaded
	lom{1.8-0.1} [LotsOMobs] (lom-1.8-0.1.jar) Unloaded
	Loaded coremods (and transformers): 
DLFMLCorePlugin (DynamicLights-1.8.jar)
  atomicstryker.dynamiclights.common.DLTransformer
	Launched Version: 1.8-Forge11.14.1.1334
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 650 Ti/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.52, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [faithful32pack.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by Lomeli12** [comment]
You forgot to install LomLib: https://lomeli12.net/minecraft-mods/lomlib/

**Comment by cemerson** [comment]
So sorry - thank you!
